image:
  name: "hashicorp/terraform:1.3.2"
  entrypoint: [""]

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/terraform  # The relative path to the root directory of the Terraform project
  TF_STAGE_NAME: ${CI_COMMIT_BRANCH} 
  TF_ADDRESS: https://gitlab.orema.com.tr/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${TF_STAGE_NAME}
  TF_USERNAME: gitlab-ci-token
  TF_PASSWORD: ${CI_JOB_TOKEN}

stages:
  - validate
  - build

before_script:
  - cd $TF_ROOT

validate:
  stage: validate
  script:
    - terraform fmt -check
build:
  stage: build
  script:
    - chmod +x init.sh
    - sh init.sh
    - terraform validate
    - echo $TF_ADDRESS
    - echo "${TF_STAGE_NAME} state saved"
