
image:
  name: "hashicorp/terraform:1.3.2"
  entrypoint: [""]

stages:
  - validate
  - test
  - build
  
before_script:
  - terraform init

validate:
  stage: validate
  script:
    - terraform validate
